app.base-url=http://192.168.0.138:8080
# Falls back to hardcoded values locally (e.g. Berlin) if env vars are not set.
app.weather.latitude=${LATITUDE:52.52437}
app.weather.longitude=${LONGITUDE:13.41053}

spring.datasource.url=jdbc:postgresql://localhost:5432/plant_tracker
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false